name: Publish Docker Image and Run Testkube Workflow

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: matecuenca/node-app:latest

  run-test:
    runs-on: ubuntu-latest

    steps:
      - uses: kubeshop/setup-testkube@v1
        with:
          organization: tkcorg_e2a9065930ed22b5
          environment: tkcenv_3c467812524b75cc
          token: ${{ secrets.TK_TOKEN_API }}

      - run: |
          testkube run testworkflow pactum-pruebas-2 -f
